name: Deploy to Cloudflare Workers

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
      
      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --env production
        env:
          # Secrets are managed via wrangler secret put
          # These are already set in Cloudflare Workers dashboard:
          # - OS_HOSTNAME
          # - OS_USERNAME
          # - OS_PASSWORD
          # - OS_DEV_ENVID
          # - MCP_SERVER_SECRET
          NODE_ENV: production
      
      - name: Deployment summary
        run: |
          echo "## Deployment Complete! 🚀" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Your MCP server is now live at:" >> $GITHUB_STEP_SUMMARY
          echo "\`https://outsystems-mcp.<your-subdomain>.workers.dev\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Next Steps:" >> $GITHUB_STEP_SUMMARY
          echo "1. Test the health endpoint: \`GET /health\`" >> $GITHUB_STEP_SUMMARY
          echo "2. Configure ChatGPT GPT with your Worker URL" >> $GITHUB_STEP_SUMMARY
          echo "3. See PUBLISHING.md for detailed instructions" >> $GITHUB_STEP_SUMMARY

